---
title: "Analyzing The Office data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r import_libraries, include=FALSE}

# import libraries
library(tidyverse)
library(schrute)
theme_set(theme_light())

# import office ratings from imdb
office_ratings <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-17/office_ratings.csv') %>%
  mutate(name = str_to_lower(str_remove_all(title, "\\.| \\(Part.*|\\: Part.*")))

# the office transcripts from the schrute package
office_transcripts <- as_tibble(theoffice) %>%
  mutate(season = as.integer(season),
         episode = as.integer(episode)) %>%
  mutate(character = str_remove_all(character, '"')) %>%
  mutate(name = str_to_lower(str_remove_all(episode_name, "\\.| \\(Part.*")))
```
### Ratings grouped by season
```{r echo = FALSE, warning = FALSE, fig.cap="Ratings grouped by season"}
# ratings grouped by season
office_ratings %>%
  group_by(season) %>%
  summarize(avg_rating = mean(imdb_rating)) %>%
  ggplot(aes(season, avg_rating)) +
  geom_line() +
  scale_x_continuous(breaks = 1:9)

```

### Ratings of each episode over 9 seasons
```{r echo = FALSE, warning = FALSE, fig.cap="Ratings of each episode over 9 seasons"}

# ratings of each episode over 9 seasons
office_ratings %>%
  mutate(title = fct_inorder(title)) %>%
  ggplot(aes(title, imdb_rating)) + 
  geom_line(group = 1) +
  geom_point(aes(color = factor(season), size = total_votes)) +
  geom_text(aes(label = title), check_overlap = TRUE, hjust = 1)
  theme(axis.text.x = element_blank(),
        panel.grid.major.x = element_blank(),
        legend.position = 'none')
```

```{r}
# popularity of the office over time
office_ratings %>%
  mutate(title = fct_inorder(title),
         episode_number = row_number()) %>%
  ggplot(aes(episode_number, imdb_rating)) + 
  geom_line(group = 1) +
  geom_smooth(group = 1) +
  geom_point(aes(color = factor(season), size = total_votes)) +
  geom_text(aes(label = title), check_overlap = TRUE, hjust = 1) +
  expand_limits(x = -10) +
  theme(panel.grid.major.x = element_blank(),
        legend.position = 'none') +
  labs(x = "Episode number",
       y = "IMDB Rating",
       title = "Popularity of The Office episodes over time",
       subtitle = "Colour represents season, size represents # of ratings")
```
### The Office Transcripts

```{r}
library(tidytext)

blacklist_words <- c("yeah", "hey", "uh", "um", "ah", "gonna")
blacklist_characters <- c("Everyone", "All", "Both", "Guy", "Girl", "Group")

# group words by character
transcript_words <- office_transcripts %>%
  group_by(character) %>%
  # filter number of lines over 30, episodes greater than 2
  filter(n() >= 100, n_distinct(episode_name) > 2) %>%
  # remove text_w_direction
  select(-text_w_direction) %>%
  unnest_tokens(word, text) %>%
  anti_join(stop_words, by = "word") %>%
  #filter out words not in blacklist_words
  filter(!word %in% blacklist_words,
         !character %in% blacklist_characters)

# counts all words per character, sorted high to low
 
michael <- transcript_words %>%
  count(character = "Michael", sort = TRUE)

michael_word_count <- michael$n

character_tf_idf <- transcript_words %>%
  add_count(word) %>%
  count(word, character) %>%
  bind_tf_idf(word, character, n) %>%
  arrange(desc(tf_idf))


```
Michael said `r michael_word_count` words throughout the whole series.

### Common words, common characters

```{r}
character_tf_idf %>%
  filter(character == "Dwight") %>%
  mutate(word = fct_reorder(word, tf_idf)) %>%
  head(20) %>%
  ggplot(aes(word, tf_idf)) +
  geom_col() + 
  coord_flip() +
  labs(x = "words",
       y = "TF-IDF of Dwight's words",
       title = "Popular words of Dwight Schrute")

character_tf_idf %>%
  filter(character %in% c("Dwight", "Jim", "Michael", "Darryl", "Kelly", "Ryan")) %>%
  group_by(character) %>%
  top_n(10, tf_idf) %>%
  ungroup() %>%
  mutate(word = reorder_within(word, tf_idf, character)) %>%
  ggplot(aes(word, tf_idf)) +
  geom_col() + 
  coord_flip() + 
  scale_x_reordered() +
  facet_wrap(~ character, scales = "free_y") +
  labs(x = "",
       y = "TF-IDF of character-word pairs")
  
```
```{r}
office_transcripts %>%
  count(character, sort = TRUE)

```

### Machine Learning

What affects the popularity of an episode?

- Season/time
- Director
- Writer
- Lines per character

```{r}
ratings_summarized <- office_ratings %>%
  group_by(name) %>%
  summarize(imdb_rating = mean(imdb_rating))

character_lines_ratings <- office_transcripts %>%
  count(character, name) %>%
  group_by(character) %>%
  filter(sum(n) > 100) %>%
  inner_join(ratings_summarized, by ="name")

character_lines_ratings %>%
  summarize(avg_rating = mean(imdb_rating),
            nb_episodes = n()) %>%
  arrange(desc(avg_rating))
```
